export const styles = {
  root: {
    minHeight: "100vh",
    background: "#0a0a0f",
    fontFamily: "system-ui, sans-serif",
    color: "#fff",
    maxWidth: 480,
    margin: "0 auto",
    position: "relative",
    overflow: "hidden",
  },

  // Login
  loginWrap: {
    minHeight: "100vh",
    background: "linear-gradient(160deg,#0a0a0f 0%,#12071a 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  loginCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 24,
    padding: "40px 28px",
    width: "100%",
    maxWidth: 360,
    textAlign: "center",
    backdropFilter: "blur(12px)",
  },
  loginLogo: { fontSize: 48, marginBottom: 8 },
  loginTitle: {
    fontSize: 32,
    fontFamily: "Georgia, serif",
    margin: "0 0 6px",
    background: "linear-gradient(90deg,#f7b733,#fc4a1a)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  loginSub: { color: "#9ca3af", fontSize: 14, margin: "0 0 28px" },
  loginLabel: { color: "#6b7280", fontSize: 12, textTransform: "uppercase", letterSpacing: 1, marginBottom: 12 },
  socialBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    width: "100%",
    padding: "12px 20px",
    borderRadius: 12,
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 600,
    marginBottom: 10,
  },
  avatarPicker: {
    width: 90,
    height: 90,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.06)",
    border: "2px dashed #374151",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    margin: "0 auto 16px",
    cursor: "pointer",
    overflow: "hidden",
    position: "relative",
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  avatarHint: { fontSize: 9, color: "#6b7280", marginTop: 4, position: "absolute", bottom: 6 },
  nameInput: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "#fff",
    fontSize: 15,
    outline: "none",
    boxSizing: "border-box",
    marginBottom: 14,
  },
  primaryBtn: {
    width: "100%",
    padding: "13px",
    borderRadius: 12,
    background: "linear-gradient(90deg,#f7b733,#fc4a1a)",
    border: "none",
    color: "#fff",
    fontSize: 15,
    fontWeight: 700,
    cursor: "pointer",
  },

  // Home
  homeWrap: {
    minHeight: "100vh",
    background: "#0a0a0f",
    paddingBottom: 40,
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 16px 12px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
  },
  headerAvatar: {
    width: 40, height: 40, borderRadius: "50%",
    background: "#1f2937",
    overflow: "hidden",
    display: "flex", alignItems: "center", justifyContent: "center",
    border: "2px solid #22c55e",
  },
  headerAvatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  premiumBadge: {
    background: "linear-gradient(90deg,#f7b733,#fc4a1a)",
    padding: "3px 10px",
    borderRadius: 20,
    fontSize: 11,
    fontWeight: 700,
  },
  logoutBtn: {
    background: "rgba(255,255,255,0.06)",
    border: "none",
    color: "#9ca3af",
    padding: "6px 12px",
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
  },

  hero: {
    margin: "16px 16px 0",
    background: "linear-gradient(135deg,rgba(247,183,51,0.12),rgba(252,74,26,0.08))",
    border: "1px solid rgba(247,183,51,0.15)",
    borderRadius: 16,
    padding: "18px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  heroText: {},
  heroDecor: { fontSize: 48, opacity: 0.6 },

  catRow: {
    display: "flex",
    gap: 8,
    padding: "14px 16px 4px",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  catBtn: {
    padding: "7px 16px",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "transparent",
    color: "#9ca3af",
    fontSize: 13,
    cursor: "pointer",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  catBtnActive: {
    background: "linear-gradient(90deg,#f7b733,#fc4a1a)",
    border: "none",
    color: "#fff",
    fontWeight: 700,
  },

  grid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 12,
    padding: "16px 16px",
  },
  card: {
    borderRadius: 14,
    overflow: "hidden",
    cursor: "pointer",
    position: "relative",
    aspectRatio: "3/4",
    transition: "transform 0.15s",
  },
  cardBg: {
    width: "100%", height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    padding: 10,
    boxSizing: "border-box",
  },
  cardTop: {
    background: "rgba(0,0,0,0.5)",
    borderRadius: 10,
    padding: "6px 8px",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  cardAvatar: {
    width: 28, height: 28, borderRadius: "50%",
    overflow: "hidden",
    background: "#374151",
    flexShrink: 0,
    display: "flex", alignItems: "center", justifyContent: "center",
    border: "1.5px solid #22c55e",
  },
  cardQuote: {
    color: "#fff",
    fontSize: 11,
    lineHeight: 1.5,
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
    fontFamily: "Georgia, serif",
    padding: "4px 0",
    flex: 1,
    display: "flex",
    alignItems: "center",
  },
  cardTag: {
    fontSize: 10,
    fontWeight: 700,
  },
  premiumLock: {
    position: "absolute",
    top: 0, left: 0, right: 0, bottom: 0,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    backdropFilter: "blur(2px)",
  },

  // Overlay & Popup
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.75)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    zIndex: 100,
    backdropFilter: "blur(4px)",
  },
  popup: {
    background: "#111827",
    borderRadius: "20px 20px 0 0",
    padding: "28px 24px 32px",
    width: "100%",
    maxWidth: 480,
    position: "relative",
    overflow: "hidden",
    textAlign: "center",
  },
  popupGlow: {
    position: "absolute",
    top: -60, left: "50%",
    transform: "translateX(-50%)",
    width: 200, height: 200,
    background: "radial-gradient(circle,rgba(247,183,51,0.2),transparent 70%)",
    pointerEvents: "none",
  },
  popupTitle: {
    fontSize: 24,
    fontFamily: "Georgia, serif",
    margin: "0 0 8px",
  },
  popupDesc: { color: "#9ca3af", fontSize: 14, margin: "0 0 20px" },
  planRow: { display: "flex", gap: 12, marginBottom: 18 },
  planCard: {
    flex: 1,
    background: "#1f2937",
    borderRadius: 12,
    padding: "14px 10px",
    border: "1px solid #374151",
  },
  planName: { fontSize: 12, color: "#9ca3af", marginBottom: 4 },
  planPrice: { fontSize: 22, fontWeight: 800, color: "#fff" },
  premiumBtn: {
    width: "100%",
    padding: 14,
    borderRadius: 12,
    background: "linear-gradient(90deg,#f7b733,#fc4a1a)",
    border: "none",
    color: "#fff",
    fontSize: 16,
    fontWeight: 700,
    cursor: "pointer",
    marginBottom: 12,
  },
  closeLink: {
    background: "none",
    border: "none",
    color: "#6b7280",
    cursor: "pointer",
    fontSize: 13,
    padding: 8,
    display: "block",
    margin: "0 auto",
  },

  toast: {
    position: "fixed",
    bottom: 30,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#22c55e",
    color: "#fff",
    padding: "10px 24px",
    borderRadius: 30,
    fontSize: 14,
    fontWeight: 600,
    zIndex: 200,
    whiteSpace: "nowrap",
  },
};
